# Introduction to Numpy

## Define Array

In [1]:
# import library numpy
import numpy as np

In [4]:
# define 1D-array from list
list_1d = [1,2,3]

array_1d = np.array(list_1d)
array_1d

array([1, 2, 3])

In [6]:
type(array_1d)

numpy.ndarray

In [7]:
# define 2D-array from list
list_2d = [[1,2,3], [4,5,6]]

array_2d = np.array(list_2d)
array_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
type(array_2d)

numpy.ndarray

In [11]:
# define numpy array from arange function
array_example = np.arange(0, 11, 2)
array_example

array([ 0,  2,  4,  6,  8, 10])

In [12]:
# np.zeros 1D array
np.zeros(3)

array([0., 0., 0.])

In [13]:
# np.zeros 2D array
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
# np.zeros 2D array
np.zeros((3,7))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [15]:
# np.ones 1D array
np.ones(3)

array([1., 1., 1.])

In [16]:
# np.ones 2D array
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
# np.ones 2D array
np.ones((3,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [22]:
# np.eye for matrix identity
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [23]:
# np.linspace for make numbers in range
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [29]:
np.linspace(1, 10, 20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [31]:
# counting values in array
len(np.linspace(1, 10, 20))

20

In [32]:
array_example = np.linspace(1, 10, 20)
len(array_example)

20

In [33]:
# random array with value 0 - 1
np.random.rand(3)

array([0.54389725, 0.90628573, 0.063785  ])

In [34]:
np.random.rand(3,3)

array([[0.58862386, 0.88552129, 0.0611287 ],
       [0.12679164, 0.5856558 , 0.86164269],
       [0.08640836, 0.84448502, 0.04545935]])

In [35]:
# random array with value in normal distribution
np.random.randn(3)

array([ 0.06101112, -1.90676908, -0.56708804])

In [36]:
np.random.randn(3,3)

array([[-1.71086393,  0.92692685, -1.38594326],
       [ 0.30998199, -0.27417729,  2.11254614],
       [ 0.70814852, -1.36334143, -0.42324814]])

In [37]:
# random array with integer value in a range
np.random.randint(1, 100)

76

In [38]:
np.random.randint(1, 100, 10)

array([43, 79, 77, 38, 46, 40, 79,  1,  6, 75])

## Array Atribute and Method

In [43]:
# shape
list_1d = [1,2,3]
array_1d = np.array(list_1d)

list_2d = [[1,2,3], [4,5,6]]
array_2d = np.array(list_2d)

list_3d = [[[1,2,3], [4,5,6], [7,8,9]], [[10,11,12], [13,14,15], [16,17,18]]]
array_3d = np.array(list_3d)

In [44]:
print(f"array 1D shape: {array_1d.shape}")
print(f"array 2D shape: {array_2d.shape}")
print(f"array 3D shape: {array_3d.shape}")

array 1D shape: (3,)
array 2D shape: (2, 3)
array 3D shape: (2, 3, 3)


In [47]:
# reshape
arr = np.arange(1, 26)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [48]:
arr.shape

(25,)

In [54]:
arr_1_25 = arr.reshape(1,25)
arr_1_25

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25]])

In [51]:
arr_1_25.shape

(1, 25)

In [58]:
arr_5_5 = arr.reshape(5,5)
arr_5_5

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [53]:
arr_5_5.shape

(5, 5)

In [59]:
arr_5_5.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [61]:
# max, min, argmax and argmin
arr = np.array([11, 5, 6, 7, 24, 22, 8, 13])

print(f"max: {np.max(arr)}")
print(f"min: {np.min(arr)}")
print(f"argmax: {np.argmax(arr)}")
print(f"argmin: {np.argmin(arr)}")

max: 24
min: 5
argmax: 4
argmin: 1


# Indexing and Selection

In [63]:
# indexing
list_3d = [
    [[1,2,3], [4,5,6], [7,8,9]],
    [[10,11,12], [13,14,15],[16,17,18]]
]
array_3d = np.array(list_3d)
array_3d.shape

(2, 3, 3)

In [70]:
angka_9 = array_3d[0][2][2]
angka_9

np.int64(9)

In [65]:
angka_14 = array_3d[1,1,1]
angka_14

np.int64(14)

In [71]:
# conditional slicing
arr = np.array([11, 5, 6, 7, 24, 22, 8, 13])

In [74]:
arr > 11

array([False, False, False, False,  True,  True, False,  True])

In [75]:
arr[arr > 11]

array([24, 22, 13])